# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rails db:seed command (or created alongside the database with db:setup).
#
# Examples:
#
#   movies = Movie.create([{ name: 'Star Wars' }, { name: 'Lord of the Rings' }])
#   Character.create(name: 'Luke', movie: movies.first)

categories = [
'Ainu',
'Albanian',
'Argentine',
'Andhra',
'Anglo-Indian',
'Arab',
'Armenian',
'Assyrian',
'Awadhi',
'Azerbaijani',
'Balochi',
'Belarusian',
'Bangladeshi',
'Bengali',
'Berber',
'Brazilian',
'Buddhist',
'Bulgarian',
'Cajun',
'Cantonese',
'Caribbean',
'Chechen',
'Chinese cuisine',
'Chinese Islamic',
'Circassian',
'Crimean Tatar',
'Cypriot',
'Danish',
'English',
'Estonian',
'French',
'Filipino',
'Georgian',
'German',
'Goan',
'Goan Catholic',
'Greek',
'Gujarati',
'Hyderabad',
'Indian cuisine',
'Indian Chinese',
'Indian Singaporean cuisine',
'Indonesian',
'Inuit',
'Irish',
'Italian-American',
'Italian cuisine',
'Jamaican',
'Japanese',
'Jewish',
'Karnataka',
'Kazakh',
'Keralite',
'Korean',
'Kurdish',
'Laotian',
'Lebanese',
'Latvian',
'Lithuanian',
'Louisiana Creole',
'Maharashtrian',
'Mangalorean',
'Malay',
'Malaysian Chinese cuisine',
'Malaysian Indian cuisine',
'Mediterranean cuisine',
'Mexican',
'Mordovian',
'Mughal',
'Native American',
'Nepalese',
'New Mexican',
'Odia',
'Parsi',
'Pashtun',
'Polish',
'Pennsylvania Dutch',
'Pakistani',
'Peranakan',
'Persian',
'Peruvian',
'Portuguese',
'Punjabi',
'Rajasthani',
'Romanian',
'Russian',
'Sami',
'Serbian',
'Sindhi',
'Slovak',
'Slovenian',
'Somali',
'South Indian',
'Soviet',
'Spanish',
'Sri Lankan',
'Taiwanese',
'Tatar',
'Thai',
'Turkish',
'Tamil',
'Udupi',
'Ukrainian',
'Vietnamese',
'Yamal',
'Zambian',
'Zanzibari]',

100.times do
  Chef.create(
    name: Faker::FunnyName.two_word_name,
    description: Faker::Restaurant.description,
    category: categories.sample,
    price_range: ["$", "$$", "$$$", "$$$$"].sample,
    location: Faker::Address.city
  )
end
